### PR TITLE
Scanpy/Scanorama Install

### PR DESCRIPTION
**Pull request by alex-wenzel**
Our last few commits - major changes are switching scanpy to install from bioconda and installing Scanorama 0.6

Scanorama has a newer version 0.6.2 available but it has some 0.6 is the newest version that still works.

### CODE REVIEW

**Comment by alex-wenzel** [comment]
The scanorama devs pushed some new pip releases with bug fixes based on errors I encountered. I'm going to evaluate if we should switch to new version (0.7.1) or stick with last stable version (0.6). Closing this pull request until that decision is made.

**Comment by alex-wenzel** [comment]
Made a couple changes to the Dockerfile to address package issues arising from discrepancies between the Python3.6/3.7 kernels in the base genepattern notebook docker container.

For now we can only use Python 3.6 notebooks. I updated to release version 1.0 for Scanorama. All of their most recent versions have a dependency error in Python 3.7 involving Annoy that I couldn't solve. Using the 3.6 kernel works fine though.

**Comment by edjuaro** [comment]
The command
`conda install -y -c bioconda scanpy==1.3.4 -n python3.6`
requires a local python3.6 environment to build locally. We can leave it as is, but it'd be good to make this a bit more generalizable in the future (i.e., we should be able to build regardless of the local conda environments).

Edit: looking at the Dockerfile, there *should* be a Python3.6 already in the container. I'm looking into this.

**Comment by alex-wenzel** [comment]
I agree - the reason I included the specific python3.6 flag was because, without it, only Python 3.7 could see Scanpy 1.3.4, and I couldn't get Scanorama to work in Python 3.7 (see above). Installing to 3.6 specifically is definitely not ideal - it was the quickest/easiest way I could think of to resolve dependencies at the time.

**Comment by edjuaro** [comment]
Yes, that makes sense. I had some issues because we are using the `latest` tag for the GPNB container, which is the best thing we can do for now (that container does not have numeric versions yet). So when I was updating it I started getting the "No space left on device" error, which has taken me through some rabbit holes. Currently trying to build another container I blew up by mistake.

**Comment by edjuaro** [comment]
Successfully built, ran a notebook inside with no problem. Pushed to Dockerhub. I've modified the dockerfile slightly. Will reflect that when I resolve conflicts.

**Pull request merged**
